config/routes.rb
Rails.application.routes.draw do
  # get all dynamic_models
  @model_symbols = []
  models = Contact.all.select(:klaas)

  models.each do |model_name|
    @model_symbols << model_name.klaas.split(" ").join("_").downcase.pluralize.to_sym
    @model_symbols.uniq!
  end
  
  # get "/contacts/:type", to: "contacts#index"
  scope '/contacts' do
    @model_symbols.each do |model_symbol|
      resources model_symbol, controller: 'contacts', as: model_symbol
    end
  end
  get "contacts/:type", to: "contacts#index"
  get "contacts/:type/:id", to: "contacts#show"
  get "contacts/:type/:id/edit", to: "contacts#edit"
  resources :contacts do
  end
  # root to: '#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_construction.rb
class ClassConstruction
    
    # def initialize(model)
    #     klass = Class.new(model) do
    #         ATTRIBUTES = attributes
    #         attr_accessor *ATTRIBUTES
    # 
    #         def initialize(*args)
    #             raise ArgumentError, "Too many arguments" if args.size > ATTRIBUTES.size
    #             ATTRIBUTES.zip(args) do |attr, val|
    #                 send "#{attr}=", val
    #             end
    #         end
    #     end
    # end
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_dynamic_attributes
  # before_save create_model_class(data[:type], data)
  
  # def initialize(data)
  #     create_model_class if !(data[:klaas] == self)
  #     debugger
  # end
  
  def self.create_model_class(klass_name, klass_vars)
    klass = Object.const_set(klass_name, Class.new(Contact))
    klass.class_eval do
      # has_dynamic_attributes
      define_method(:initialize) do |params|
        super(params)
        klass_vars.keys.each_with_index do |name, i|
          instance_variable_set("@"+name[i], name[i])
        end
      end
    end
    return klass
  end
  
  # def self.find
  #   find.where(klaas: !("Vin"))
  # end
  
  # def to_param
  #   uri = "#{id}-#{name}"
  #   debugger
  # end
end

app/models/contact_attribute.rb
class ContactAttribute < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :create_classes#, except: [:index]
  
  def create_classes
    # debugger
    
    model_names = []
    @dynamic_models = []
    # Contact.all.select(:klaas).each { |model_name| name << model_name.klaas }
    Contact.all.select(:klaas).each do |model_name|
      # Add all the model_names to an array, so we can create classes from them
      model_names.push model_name.klaas
      model_names.uniq!
    end
    
    # We only want to create a model once for each model_name
    model_names.each do |dynamic_model|
      @dynamic_models.push Contact.create_model_class dynamic_model, Contact.find_by_klaas(dynamic_model)
    end
    
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
      @dynamic_models.each do |model_name|
        instance_variable_set("@"+model_name.to_s.pluralize.downcase, model_name.where(klaas: model_name.to_s))
        # debugger
      end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    set_contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    klass = Contact.create_model_class(params[:contact][:klaas], params[:contact])
    
    set_contact = klass.new(contact_params)
    

    respond_to do |format|
      if set_contact.save
        format.html { redirect_to contact_url set_contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: (contact_url set_contact) }
      else
        format.html { render :new }
        format.json { render json: set_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if set_contact.update(contact_params)
        format.html { redirect_to contact_url set_contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: (contact_url set_contact) }
      else
        format.html { render :edit }
        format.json { render json: set_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    set_contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      klass = Contact.create_model_class(Contact.find(params[:id]).klaas, params[:contact])
      # @contact = klass.find(params[:id])
      instance_variable_set("@"+klass.to_s.downcase,klass.find(params[:id]))
      # debugger
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      debugger
        params.require(:vin).permit(*Contact.new.dynamic_attributes.map(&:name), :name, :klaas)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper  
  def some_path(some)
    # We want the route to be something like "/contacts/modelname/id"
    "/#{path_base(some)}/#{some.klaas.underscore.downcase}/#{some.id}"
  end
  
  def some_edit_path(some)
    "/#{path_base(some)}/#{some.klaas.downcase}/#{some.id}/edit"
  end
  
  def delete_some_path(some)
    # We want the route to be something like "/contacts/modelname/id"
    "#{path_base(some)}/#{some.id}"
  end

  private
    def path_base(some)
      Contact.create_model_class(some.klaas, some).superclass.name.underscore.pluralize
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
    
    def dynamic_attribute_inputs(form, model)
        inputs = model.dynamic_attributes.map do |attr|
            options = {
                label: attr.display_name,
                as: datatype_mapping(attr.datatype)
            }
            form.input attr.name, options
        end

        safe_join inputs
    end
    
    def datatype_mapping(type)
        case type
            when ActiveDynamic::DataType::Text then :text
            when ActiveDynamic::DataType::Integer then :integer
            else :string
        end
    end
    
    # Generate dynamic paths
    def all_instances_path model
      Rails.application.routes.url_helpers.send("#{model.klaas.downcase.pluralize}_path")
    end
    
    def instance_path model
      Rails.application.routes.url_helpers.send("#{model.klaas.downcase}_path", model)
    end
    
    def new_instance_path model
      Rails.application.routes.url_helpers.send("new_#{model.klaas.downcase}_path")
    end
    
    def edit_instance_path model
      Rails.application.routes.url_helpers.send("edit_#{model.klaas.downcase}_path", model)
    end
end

app/views/contacts/_form.html.erb
<%= simple_form_for @vin do |form| %>
  <% if @vin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vin.errors.count, "error") %> prohibited this @vin from being saved:</h2>

      <ul>
      <% @vin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :vin_name %>
  </div>
  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :klaas, id: :vin_type %>
  </div>

  <div class="field">
      <%= dynamic_attribute_inputs(form, @vin) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= debugger;render 'form' %>

<%= link_to 'Show', @vin %> |
<%= link_to 'Back', vins_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vins.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.age %></td>
        <td>Type: <%= contact.klaas %></td>
        <td><%= link_to 'Show', instance_path(contact) %></td>
        <td><%= link_to 'Edit', edit_instance_path(contact)%></td>
        <td><%= link_to 'Destroy', Rails.application.routes.url_helpers.send("#{contact.klaas.downcase}_path", contact), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vin.name %>
</p>

<%= link_to 'Edit', edit_vin_path(@vin.id, type: @vin.klaas) %> |
<%= link_to 'Back', vins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Genealogie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>